import PDFKit
import UIKit

// MARK: - PDF Receipt Renderer
enum PDFReceiptRenderer {
    static func makePDF(from receipt: PDFReceiptData) -> Data {
        let pageRect = CGRect(x: 0, y: 0, width: 595, height: 842)
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)

        return renderer.pdfData { context in
            context.beginPage()

            let margin: CGFloat = 44
            var y: CGFloat = 54
            let contentWidth = pageRect.width - (margin * 2)

            drawText(
                "CakeLab",
                at: CGPoint(x: margin, y: y),
                width: contentWidth,
                font: .boldSystemFont(ofSize: 30),
                color: UIColor(red: 0.365, green: 0.216, blue: 0.078, alpha: 1)
            )
            y += 38

            drawText(
                receipt.title,
                at: CGPoint(x: margin, y: y),
                width: contentWidth,
                font: .systemFont(ofSize: 17, weight: .semibold),
                color: .darkGray
            )
            y += 40

            drawDivider(x: margin, y: y, width: contentWidth)
            y += 28

            y = drawRow(label: "Receipt No.", value: receipt.receiptNumber, x: margin, y: y, width: contentWidth)
            y = drawRow(label: "Cake Order", value: receipt.cakeName, x: margin, y: y, width: contentWidth)
            y = drawRow(label: receipt.payerLabel, value: receipt.payerName, x: margin, y: y, width: contentWidth)
            y = drawRow(label: receipt.receiverLabel, value: receipt.receiverName, x: margin, y: y, width: contentWidth)
            y = drawRow(label: "Payment Method", value: receipt.paymentMethod, x: margin, y: y, width: contentWidth)
            y = drawRow(label: "Status", value: receipt.status.capitalized, x: margin, y: y, width: contentWidth)
            y = drawRow(label: "Paid At", value: formattedDate(receipt.paidAt), x: margin, y: y, width: contentWidth)

            y += 18
            drawDivider(x: margin, y: y, width: contentWidth)
            y += 28

            y = drawAmountRow(label: receipt.subtotalLabel, amount: receipt.subtotal, x: margin, y: y, width: contentWidth)
            y = drawAmountRow(label: "Service Fee", amount: receipt.serviceFee, x: margin, y: y, width: contentWidth)
            y += 8
            drawDivider(x: margin, y: y, width: contentWidth)
            y += 22
            _ = drawAmountRow(
                label: receipt.totalLabel,
                amount: receipt.total,
                x: margin,
                y: y,
                width: contentWidth,
                isTotal: true
            )

            drawText(
                "Generated by CakeLab",
                at: CGPoint(x: margin, y: pageRect.height - 72),
                width: contentWidth,
                font: .systemFont(ofSize: 11),
                color: .gray,
                alignment: .center
            )
        }
    }

    private static func drawRow(label: String, value: String, x: CGFloat, y: CGFloat, width: CGFloat) -> CGFloat {
        drawText(label, at: CGPoint(x: x, y: y), width: 160, font: .systemFont(ofSize: 12), color: .gray)
        drawText(value, at: CGPoint(x: x + 178, y: y), width: width - 178, font: .systemFont(ofSize: 13, weight: .medium), color: .black)
        return y + 28
    }

    private static func drawAmountRow(label: String, amount: Double, x: CGFloat, y: CGFloat, width: CGFloat, isTotal: Bool = false) -> CGFloat {
        let font = isTotal ? UIFont.boldSystemFont(ofSize: 16) : UIFont.systemFont(ofSize: 13, weight: .medium)
        drawText(label, at: CGPoint(x: x, y: y), width: width / 2, font: font, color: .black)
        drawText(currency(amount), at: CGPoint(x: x + width / 2, y: y), width: width / 2, font: font, color: .black, alignment: .right)
        return y + 28
    }

    private static func drawDivider(x: CGFloat, y: CGFloat, width: CGFloat) {
        let path = UIBezierPath()
        path.move(to: CGPoint(x: x, y: y))
        path.addLine(to: CGPoint(x: x + width, y: y))
        UIColor(red: 0.88, green: 0.86, blue: 0.83, alpha: 1).setStroke()
        path.lineWidth = 1
        path.stroke()
    }

    private static func drawText(
        _ text: String,
        at point: CGPoint,
        width: CGFloat,
        font: UIFont,
        color: UIColor,
        alignment: NSTextAlignment = .left
    ) {
        let paragraph = NSMutableParagraphStyle()
        paragraph.alignment = alignment
        let attributes: [NSAttributedString.Key: Any] = [
            .font: font,
            .foregroundColor: color,
            .paragraphStyle: paragraph
        ]
        text.draw(
            with: CGRect(x: point.x, y: point.y, width: width, height: 42),
            options: [.usesLineFragmentOrigin, .usesFontLeading],
            attributes: attributes,
            context: nil
        )
    }

    private static func formattedDate(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .short
        return formatter.string(from: date)
    }

    private static func currency(_ value: Double) -> String {
        "LKR \(Int(value).formatted())"
    }
}
